name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to VPS
      run: |
        # SSH into the VPS and run commands
        ssh -o StrictHostKeyChecking=no deploy@66.42.103.234 << 'EOF'
          # Go to the app directory on the VPS
          cd /var/www/app

          # Pull the latest changes from the main branch
          git pull origin main

          # Install dependencies
          yarn install

          # Build the web assets
          yarn rw build

          # Run database migrations (ensure prisma is properly set up)
          yarn rw prisma migrate deploy

          # Restart the app using pm2
          pm2 restart all
        EOF
